package com.badmanners.murglar.lib.core.model.event

import com.badmanners.murglar.lib.core.node.NodeResolver
import com.badmanners.murglar.lib.core.utils.contract.Model
import java.io.Serializable


/**
 * Event can be [PlayerEvent] (called by the client app) or [CustomAction] (called by the user from node menu).
 *
 * @see NodeResolver.handleEvent
 */
sealed interface Event : Serializable

/**
 * Events that can be generated by the player.
 */
sealed interface PlayerEvent : Event {

    object TrackStart : PlayerEvent {
        private fun readResolve(): Any = TrackStart
    }

    @Model
    data class TrackEnd(val endTimeMs: Int) : PlayerEvent

    object DislikeTrack : PlayerEvent {
        private fun readResolve(): Any = DislikeTrack
    }

    object DislikeArtist : PlayerEvent {
        private fun readResolve(): Any = DislikeArtist
    }
}

/**
 * Parent interface for custom node actions.
 */
interface CustomAction : Event