package com.badmanners.murglar.lib.core.model.event

import com.badmanners.murglar.lib.core.node.NodeResolver


/**
 * Event can be [PlayerEvent] (called by the client app) or [CustomAction] (called by the user from node menu).
 *
 * @see NodeResolver.handleEvent
 */
sealed interface Event

/**
 * Events that can be generated by the player.
 */
sealed interface PlayerEvent : Event {
    object TrackStart : PlayerEvent
    data class TrackEnd(val endTimeMs: Int) : PlayerEvent
    object DislikeTrack : PlayerEvent
    object DislikeArtist : PlayerEvent
}

/**
 * Parent interface for custom node actions.
 */
interface CustomAction : Event